-- Report data extraction (extract.py)
-- Generated by 04_SQL_Data/export_all_sql.py from the saved scripts. Read-only SELECTs.
-- DB: order_management_copy unless the query name says [DB: ledsone] (eBay ads: ebay_campaigns).

-- Q1. SQL_ORDERS: sales, orders, units, price basis per eBay ID + SKU (Completed)
SELECT ss_name, market_place, item_id, sku, CASE WHEN order_date >= '2025-09-01' AND order_date < '2025-10-01' THEN 'LY'
                      WHEN order_date >= '2026-09-01' AND order_date < '2026-10-01' THEN 'TY' END AS per,
       SUM(COALESCE(order_total,0))::float AS sales,
       COUNT(DISTINCT order_id) AS orders,
       SUM(COALESCE(quantity,0))::float AS units,
       SUM(COALESCE(item_price,0)*COALESCE(quantity,0))::float AS price_x_qty
FROM public.order_transaction
WHERE source_name='EBAY' AND order_status='Completed' AND ss_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede')
  AND ((order_date >= '2025-09-01' AND order_date < '2025-10-01') OR (order_date >= '2026-09-01' AND order_date < '2026-10-01'))
GROUP BY 1,2,3,4,5;

-- Q2. SQL_LISTING_ORDERS: distinct orders per eBay ID
SELECT ss_name, market_place, item_id, CASE WHEN order_date >= '2025-09-01' AND order_date < '2025-10-01' THEN 'LY'
                      WHEN order_date >= '2026-09-01' AND order_date < '2026-10-01' THEN 'TY' END AS per,
       COUNT(DISTINCT order_id) AS orders
FROM public.order_transaction
WHERE source_name='EBAY' AND order_status='Completed' AND ss_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede')
  AND ((order_date >= '2025-09-01' AND order_date < '2025-10-01') OR (order_date >= '2026-09-01' AND order_date < '2026-10-01'))
GROUP BY 1,2,3,4;

-- Q3. SQL_TRAFFIC: views (click), impressions, days per eBay ID
SELECT sub_source_name, market_place, ref_id, CASE WHEN date >= '2025-09-01' AND date < '2025-10-01' THEN 'LY'
                      WHEN date >= '2026-09-01' AND date < '2026-10-01' THEN 'TY' END AS per,
       SUM(COALESCE(click,0))::float AS views, SUM(COALESCE(impression,0))::float AS impr, COUNT(DISTINCT date) AS days
FROM public.traffic_data
WHERE which_channel=2 AND sub_source_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND ((date >= '2025-09-01' AND date < '2025-10-01') OR (date >= '2026-09-01' AND date < '2026-10-01'))
GROUP BY 1,2,3,4;

-- Q4. SQL_ADS [DB: ledsone]: listing-level PPC per eBay ID and strategy (ebay_campaigns.listing_performance)
SELECT s.name AS ss_name, CASE c.marketplace_id WHEN 'EBAY_GB' THEN 'UK' WHEN 'EBAY_DE' THEN 'Germany' WHEN 'EBAY_FR' THEN 'France'
              WHEN 'EBAY_US' THEN 'US' WHEN 'EBAY_IT' THEN 'Italy' WHEN 'EBAY_ES' THEN 'Spain' WHEN 'EBAY_CA' THEN 'Canada'
              ELSE c.marketplace_id END AS marketplace, lp.ebay_listing_id::text, CASE WHEN lp.date >= '2025-09-01' AND lp.date < '2025-10-01' THEN 'LY'
                      WHEN lp.date >= '2026-09-01' AND lp.date < '2026-10-01' THEN 'TY' END AS per,
       c.campaign_type AS strat,
       SUM(lp.impressions)::float, SUM(lp.clicks)::float, SUM(lp.ad_fees_listing_currency)::float,
       SUM(lp.sale_amount_listing_currency)::float, SUM(lp.attributed_sales)::float
FROM ebay_campaigns.listing_performance lp
JOIN ebay_campaigns.campaigns c ON c.campaign_id = lp.campaign_id
JOIN order_management.sub_source s ON s.id = c.sub_source
WHERE s.name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND c.campaign_type IN ('ON_SITE','COST_PER_SALE')
  AND ((lp.date >= '2025-09-01' AND lp.date < '2025-10-01') OR (lp.date >= '2026-09-01' AND lp.date < '2026-10-01'))
GROUP BY 1,2,3,4,5;

-- Q5. SQL_CREATED [DB: ledsone]: earliest listings.ebay_listings.created_at per eBay ID ("Not live in Sep 2025" label)
SELECT item_id::text, MIN(created_at)::date::text
FROM listings.ebay_listings
WHERE item_id::text = ANY(ARRAY['317754733734']::text[])
GROUP BY 1  -- example: the build passes every eBay ID in scope;

-- Q6. SQL_SEGMENT: analytics.ph_segment labels (extracted; not used for the workbook Segment)
SELECT sub_source_name, market_place, ref_id,
       string_agg(DISTINCT performance_segment_name, ' / ' ORDER BY performance_segment_name)
FROM analytics.ph_segment
WHERE which_channel=2 AND sub_source_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND period_start='2026-09-15' AND period_end='2026-09-28'
GROUP BY 1,2,3;

-- Q7. SQL_LISTING_SKU: listing_data SKUs for IDs with no Completed order
SELECT sub_source_name, market_place, ref_id, array_agg(DISTINCT btrim(sku) ORDER BY btrim(sku))
FROM public.listing_data
WHERE which_channel=2 AND sub_source_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND wrong_sku=0 AND sku IS NOT NULL AND btrim(sku)<>''
GROUP BY 1,2,3;

-- Q8. SQL_DAYS: traffic/order day coverage
SELECT 'traffic', sub_source_name, market_place, CASE WHEN date >= '2025-09-01' AND date < '2025-10-01' THEN 'LY'
                      WHEN date >= '2026-09-01' AND date < '2026-10-01' THEN 'TY' END, COUNT(DISTINCT date), MIN(date)::text, MAX(date)::text
FROM public.traffic_data WHERE which_channel=2 AND sub_source_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND ((date >= '2025-09-01' AND date < '2025-10-01') OR (date >= '2026-09-01' AND date < '2026-10-01')) GROUP BY 1,2,3,4
UNION ALL
SELECT 'orders', ss_name, market_place, CASE WHEN order_date >= '2025-09-01' AND order_date < '2025-10-01' THEN 'LY'
                      WHEN order_date >= '2026-09-01' AND order_date < '2026-10-01' THEN 'TY' END, COUNT(DISTINCT order_date::date), MIN(order_date)::date::text, MAX(order_date)::date::text
FROM public.order_transaction WHERE source_name='EBAY' AND order_status='Completed' AND ss_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND ((order_date >= '2025-09-01' AND order_date < '2025-10-01') OR (order_date >= '2026-09-01' AND order_date < '2026-10-01')) GROUP BY 1,2,3,4;

-- Q9. SQL_STATUS: order status mix
SELECT ss_name, market_place, CASE WHEN order_date >= '2025-09-01' AND order_date < '2025-10-01' THEN 'LY'
                      WHEN order_date >= '2026-09-01' AND order_date < '2026-10-01' THEN 'TY' END, order_status,
       COUNT(*), SUM(COALESCE(order_total,0))::float
FROM public.order_transaction WHERE source_name='EBAY' AND ss_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND ((order_date >= '2025-09-01' AND order_date < '2025-10-01') OR (order_date >= '2026-09-01' AND order_date < '2026-10-01'))
GROUP BY 1,2,3,4;

