"""Write every SQL statement used by the pipeline as plain .sql files.

Reads the SQL directly from the saved scripts in this folder tree (no DB connection):
  05_HTML_Report/Build/extract.py            -> Query_Results/../Extraction_Queries.sql  (report data)
  04_SQL_Data/Validation_Queries/validate_data.py -> Validation_Queries/validate_data_queries.sql
  04_SQL_Data/Validation_Queries/audit_fields.py  -> Validation_Queries/audit_fields_queries.sql
Parameters are substituted with the literal values the pipeline uses.
"""
import importlib.util, os, pathlib, sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
SS = "('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede')"


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def render(sql, extra=None):
    sql = sql.replace("%(ss)s", SS)
    for k, v in (extra or {}).items():
        sql = sql.replace(f"%({k})s", f"'{v}'")
    return sql.strip()


def write(path, title, items):
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"-- {title}\n-- Generated by 04_SQL_Data/export_all_sql.py from the saved scripts. Read-only SELECTs.\n"
                "-- DB: order_management_copy unless the query name says [DB: ledsone] (eBay ads: ebay_campaigns).\n\n")
        for i, (name, sql) in enumerate(items, 1):
            f.write(f"-- Q{i}. {name}\n{sql};\n\n")
    print(f"{path.relative_to(ROOT)}: {len(items)} queries")


# 1. report extraction (extract.py)
ex = load(ROOT / "05_HTML_Report" / "Build" / "extract.py", "extract")
seg = {"s": ex.SEG_PERIOD[0], "e": ex.SEG_PERIOD[1]}
write(HERE / "Extraction_Queries" / "extract_queries.sql", "Report data extraction (extract.py)", [
    ("SQL_ORDERS: sales, orders, units, price basis per eBay ID + SKU (Completed)", render(ex.SQL_ORDERS)),
    ("SQL_LISTING_ORDERS: distinct orders per eBay ID", render(ex.SQL_LISTING_ORDERS)),
    ("SQL_TRAFFIC: views (click), impressions, days per eBay ID", render(ex.SQL_TRAFFIC)),
    ("SQL_ADS [DB: ledsone]: listing-level PPC per eBay ID and strategy (ebay_campaigns.listing_performance)", render(ex.SQL_ADS)),
    ("SQL_CREATED [DB: ledsone]: earliest listings.ebay_listings.created_at per eBay ID (\"Not live in Sep 2025\" label)",
     ex.SQL_CREATED.replace("%(ids)s", "ARRAY['317754733734']::text[]").strip() + "  -- example: the build passes every eBay ID in scope"),
    ("SQL_SEGMENT: analytics.ph_segment labels (extracted; not used for the workbook Segment)", render(ex.SQL_SEGMENT, seg)),
    ("SQL_LISTING_SKU: listing_data SKUs for IDs with no Completed order", render(ex.SQL_LISTING_SKU)),
    ("SQL_DAYS: traffic/order day coverage", render(ex.SQL_DAYS)),
    ("SQL_STATUS: order status mix", render(ex.SQL_STATUS)),
])

# 2. reconciliation (validate_data.py)
vd = load(HERE / "Validation_Queries" / "validate_data.py", "validate_data")
write(HERE / "Validation_Queries" / "validate_data_queries.sql", "Source-vs-dataset reconciliation (validate_data.py)",
      [(f"{k}: independent source totals", render(v)) for k, v in vd.SQL.items()]
      + [("ads [DB: ledsone]: independent ad totals per strategy (marketplace mapped in Python)", render(vd.SQL_ADS_LEDSONE))])

# 3. field audit (audit_fields.py) - capture the statements its source() function executes
af = load(HERE / "Validation_Queries" / "audit_fields.py", "audit_fields")
captured = []


class Cur:
    def execute(self, sql, params=None):
        captured.append(render(sql))
    def fetchall(self): return []
    def fetchone(self): return (0,)


class Con:
    def cursor(self): return Cur()
    def set_session(self, **k): pass
    def close(self): pass


af.psycopg2.connect = lambda *a, **k: Con()
af.ledsone_dsn = lambda: "not-used"
os.environ.setdefault("DATABASE_URL", "not-used")   # source() reads it; the fake connection ignores it
af.source()
names = ["Sales and listing orders per period", "Views and impressions per period", "eBay IDs in orders ∪ traffic",
         "Ad metrics per period and strategy [DB: ledsone]", "eBay IDs with ads [DB: ledsone] (unioned with the above in Python)",
         "Unique SKUs in order data"]
write(HERE / "Validation_Queries" / "audit_fields_queries.sql", "3-way field audit (audit_fields.py)", list(zip(names, captured)))
if len(captured) != len(names):
    sys.exit(f"expected {len(names)} audit queries, captured {len(captured)}")
