-- 3-way field audit (audit_fields.py)
-- Generated by 04_SQL_Data/export_all_sql.py from the saved scripts. Read-only SELECTs.
-- DB: order_management_copy unless the query name says [DB: ledsone] (eBay ads: ebay_campaigns).

-- Q1. Sales and listing orders per period
SELECT CASE WHEN order_date < '2026-01-01' THEN 'LY' ELSE 'TY' END, SUM(COALESCE(order_total,0)), COUNT(DISTINCT (item_id, order_id)),
                    COUNT(DISTINCT sku), COUNT(*) FILTER (WHERE sku IS NULL OR btrim(sku)='')
                    FROM public.order_transaction WHERE source_name='EBAY' AND order_status='Completed'
                    AND ss_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND ((order_date >= '2025-09-01' AND order_date < '2025-10-01') OR (order_date >= '2026-09-01' AND order_date < '2026-10-01')) GROUP BY 1;

-- Q2. Views and impressions per period
SELECT CASE WHEN date < '2026-01-01' THEN 'LY' ELSE 'TY' END, SUM(COALESCE(click,0)), SUM(COALESCE(impression,0))
                    FROM public.traffic_data WHERE which_channel=2 AND sub_source_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND ((date >= '2025-09-01' AND date < '2025-10-01') OR (date >= '2026-09-01' AND date < '2026-10-01')) GROUP BY 1;

-- Q3. eBay IDs in orders ∪ traffic
SELECT ss_name, market_place, item_id FROM public.order_transaction WHERE source_name='EBAY' AND order_status='Completed' AND ss_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND ((order_date >= '2025-09-01' AND order_date < '2025-10-01') OR (order_date >= '2026-09-01' AND order_date < '2026-10-01'))
        UNION SELECT sub_source_name, market_place, ref_id FROM public.traffic_data WHERE which_channel=2 AND sub_source_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND ((date >= '2025-09-01' AND date < '2025-10-01') OR (date >= '2026-09-01' AND date < '2026-10-01'));

-- Q4. Ad metrics per period and strategy [DB: ledsone]
SELECT CASE WHEN lp.date < '2026-01-01' THEN 'LY' ELSE 'TY' END, c.campaign_type, SUM(lp.impressions), SUM(lp.clicks), SUM(lp.ad_fees_listing_currency),
                     SUM(lp.sale_amount_listing_currency), COUNT(DISTINCT (s.name, c.marketplace_id, lp.ebay_listing_id)) FROM ebay_campaigns.listing_performance lp JOIN ebay_campaigns.campaigns c ON c.campaign_id=lp.campaign_id
                  JOIN order_management.sub_source s ON s.id=c.sub_source
                  WHERE s.name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND c.campaign_type IN ('ON_SITE','COST_PER_SALE') AND ((lp.date >= '2025-09-01' AND lp.date < '2025-10-01') OR (lp.date >= '2026-09-01' AND lp.date < '2026-10-01')) GROUP BY 1,2;

-- Q5. eBay IDs with ads [DB: ledsone] (unioned with the above in Python)
SELECT DISTINCT s.name, c.marketplace_id, lp.ebay_listing_id::text FROM ebay_campaigns.listing_performance lp JOIN ebay_campaigns.campaigns c ON c.campaign_id=lp.campaign_id
                  JOIN order_management.sub_source s ON s.id=c.sub_source
                  WHERE s.name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND c.campaign_type IN ('ON_SITE','COST_PER_SALE') AND ((lp.date >= '2025-09-01' AND lp.date < '2025-10-01') OR (lp.date >= '2026-09-01' AND lp.date < '2026-10-01'));

-- Q6. Unique SKUs in order data
SELECT COUNT(DISTINCT sku) FROM public.order_transaction WHERE source_name='EBAY' AND order_status='Completed'
                    AND ss_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND ((order_date >= '2025-09-01' AND order_date < '2025-10-01') OR (order_date >= '2026-09-01' AND order_date < '2026-10-01'));

