-- Source-vs-dataset reconciliation (validate_data.py)
-- Generated by 04_SQL_Data/export_all_sql.py from the saved scripts. Read-only SELECTs.
-- DB: order_management_copy unless the query name says [DB: ledsone] (eBay ads: ebay_campaigns).

-- Q1. sales: independent source totals
SELECT ss_name, market_place, CASE WHEN order_date < '2026-01-01' THEN 'LY' ELSE 'TY' END, SUM(COALESCE(order_total,0))::float,
                 COUNT(DISTINCT order_id), COUNT(DISTINCT (item_id, order_id)), COUNT(DISTINCT item_id), COUNT(DISTINCT sku),
                 COUNT(*) FILTER (WHERE sku IS NULL OR btrim(sku)=''), COUNT(*)
               FROM public.order_transaction WHERE source_name='EBAY' AND order_status='Completed'
                 AND ss_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND ((order_date >= '2025-09-01' AND order_date < '2025-10-01') OR (order_date >= '2026-09-01' AND order_date < '2026-10-01')) GROUP BY 1,2,3;

-- Q2. views: independent source totals
SELECT sub_source_name, market_place, CASE WHEN date < '2026-01-01' THEN 'LY' ELSE 'TY' END, SUM(COALESCE(click,0))::float, COUNT(DISTINCT ref_id), SUM(COALESCE(impression,0))::float
               FROM public.traffic_data WHERE which_channel=2 AND sub_source_name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede')
                 AND ((date >= '2025-09-01' AND date < '2025-10-01') OR (date >= '2026-09-01' AND date < '2026-10-01')) GROUP BY 1,2,3;

-- Q3. ads [DB: ledsone]: independent ad totals per strategy (marketplace mapped in Python)
SELECT s.name, c.marketplace_id, CASE WHEN lp.date < '2026-01-01' THEN 'LY' ELSE 'TY' END, c.campaign_type,
                 SUM(lp.impressions)::float, SUM(lp.clicks)::float, SUM(lp.ad_fees_listing_currency)::float, SUM(lp.sale_amount_listing_currency)::float
               FROM ebay_campaigns.listing_performance lp
               JOIN ebay_campaigns.campaigns c ON c.campaign_id=lp.campaign_id
               JOIN order_management.sub_source s ON s.id=c.sub_source
               WHERE s.name IN ('so_926407', 'led_sone', 'electricalsone', 'huettenlampen', 'ledsonede') AND c.campaign_type IN ('ON_SITE','COST_PER_SALE') AND ((lp.date >= '2025-09-01' AND lp.date < '2025-10-01') OR (lp.date >= '2026-09-01' AND lp.date < '2026-10-01'))
               GROUP BY 1,2,3,4;

